### ISSUE TITLE
run_id = f"OpenELM-450M_LR-{lr}_OA_{str(uuid.uuid4())}"

### ISSUE THREAD

**Issue by elliotthwang** [geronimi73/3090_shorts#1]
Thank you your  OPENELM ipynb tried a full finetune with HuggingFace SFTTrainer.

However, could you kind to advice how to set run_id = f"OpenELM-450M_LR-{lr}_OA_{str(uuid.uuid4())}" accordingly.

Regards

**Comment by geronimi73** [comment]
`run_id` is just a string that uniquely identifies this run, it's only used for naming the output dir and the WANDB run. i have the bad habit of putting too much information in there. 

these are the relevant lines where it is used:
```python
training_arguments = TrainingArguments(
    output_dir = f"out_{run_id}",

...

wandb.init(
    project = "OpenELM", 
    name = run_id,
).log_code(include_fn=lambda path: path.endswith(".py") or path.endswith(".ipynb"))


```

**Comment by elliotthwang** [comment]
Thanks for  your replying promptly!

Is it I could ignore the run_id  setting?

**Comment by geronimi73** [comment]
yes

**Comment by elliotthwang** [comment]
How about the bnb_config peft_config,
should I put them into your finetune codes?

Thanks!

**Comment by geronimi73** [comment]
> How about the bnb_config peft_config, should I put them into your finetune codes?

None of those. The training code in the notebook is without quantization of the base model and no PEFT. It's a full finetune of a bfloat16 model

**Comment by elliotthwang** [comment]
Got!

Thanks
